//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PushNotification_SignalR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class contact
    {
        public int Contact_Id { get; set; }
        public string Contact_Name { get; set; }
        public string Contact_No { get; set; }
        public System.DateTime AddedOn { get; set; }
    }
}
